#ifndef STYLE_H
#define STYLE_H

#define GUI_AUTOSIZE -1
#define GUI_NOCOLOR -1
#define GUI_FILL true

#define GUI_WINDOW_DEFAULT_TOP 0
#define GUI_WINDOW_DEFAULT_LEFT 0
#define GUI_WINDOW_DEFAULT_WIDTH 800
#define GUI_WINDOW_DEFAULT_HEIGHT 600

#endif
