/*
 * style.h
 *
 *  Created on: Jun 15, 2018
 *      Author: Gyula
 */

#ifndef STYLE_H_
#define STYLE_H_

#include <graphics.h>

#define GUI_STYLE_NOCOLOR					-1
#define GUI_STYLE_COLOR						LIGHTGRAY
#define GUI_STYLE_COLOR_PUSHED				DARKGRAY
#define GUI_STYLE_BORDER_SIZE				1
#define GUI_STYLE_BORDER_COLOR				DARKGRAY
#define GUI_STYLE_BORDER_COLOR_SELECTED		WHITE

#define GUI_STYLE_CANVAS_COLOR 					GUI_STYLE_COLOR
#define GUI_STYLE_CANVAS_COLOR_PUSHED			GUI_STYLE_COLOR_PUSHED
#define GUI_STYLE_CANVAS_BORDER_SIZE			GUI_STYLE_BORDER_SIZE
#define GUI_STYLE_CANVAS_BORDER_COLOR			GUI_STYLE_BORDER_COLOR
#define GUI_STYLE_CANVAS_BORDER_COLOR_SELECTED	GUI_STYLE_BORDER_COLOR_SELECTED


#endif /* STYLE_H_ */
