/*
 * solid.h
 *
 *  Created on: Jun 25, 2018
 *      Author: Gyula
 */

#ifndef GUI_THEMES_SOLID_H_
#define GUI_THEMES_SOLID_H_

#include "../defs.h"

#define MARGIN_SIZE_HORIZONTAL		4
#define MARGIN_SIZE_VERTICAL		4

#define BORDER_SIZE					1
#define BORDER_COLOR				DARKGRAY
#define BORDER_COLOR_SELECTED		WHITE
#define BORDER_COLOR_DISABLED		DARKGRAY
#define BORDER_COLOR_PUSHED			DARKGRAY

#define PADDING_SIZE_HORIZONTAL		12
#define PADDING_SIZE_VERTICAL		4

#define TEXT_SIZE					1
#define TEXT_COLOR					BLACK
#define TEXT_COLOR_PUSHED			BLACK
#define TEXT_COLOR_SELECTED			BLACK
#define TEXT_COLOR_DISABLED			DARKGRAY

#define BOX_COLOR					LIGHTGRAY
#define BOX_COLOR_PUSHED			DARKGRAY
#define BOX_COLOR_SELECTED			LIGHTGRAY
#define BOX_COLOR_DISABLED			LIGHTGRAY



#endif /* GUI_THEMES_SOLID_H_ */
